export const electronics = [
  "wok",
  "water jug",
  "teapot",
  "coffeepot",
  "cellular telephone",
  "cellular phone",
  "cellphone",
  "mobile phone",
  "Crock Pot",
  "dial telephone",
  "digital watch",
  "digital clock",
  "dishwasher",
  "dish washer",
  "dishwashing machine",
  "electric fan",
  "blower",
  "espresso maker",
  "hand blower",
  "blow dryer",
  "blow drier",
  "hair dryer",
  "hair drier",
  "hand-held computer",
  "hand-held microcomputer",
  "home theater",
  "home theatre",
  "iPod",
  "iron",
  "microwave",
  "radiator",
  "laptop",
  "refrigerator",
  "icebox",
  "stove",
  "television",
  "television system",
  "toaster",
  "vacuum",
  "vacuum cleaner",
];
